using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using PixelDefense.App;
using PixelDefense.Core;
using UnityEditor;
using UnityEngine;

namespace PixelDefense.EditorTools
{
    /// <summary>
    /// Builds the main campaign deterministically: designs each dragon (color runs, stripes), splits each color's
    /// scales into cannon ammo, derives a just-in-time deploy order, perturbs it (parking pressure), deals it into
    /// columns, proves it solvable, then tunes the crawl speed with the bot to a target safety margin.
    /// </summary>
    public static class CampaignGenerator
    {
        private const int SolverBudget = 150000;
        private const float BotReaction = 0.9f;
        private const int Attempts = 40;
        private const float MinSpeed = 0.35f;
        private const float MaxSpeed = 4.5f;

        private static readonly char[] Vivid = { 'O', 'G', 'B', 'R', 'Y', 'P', 'C', 'K', 'W', 'L' };

        [MenuItem("Pixel Defense/Levels/Generate Campaign", priority = 60)]
        public static void GenerateMenu()
        {
            string report = Generate();
            Debug.Log(report);
        }

        public static string Generate()
        {
            var config = AssetDatabase.LoadAssetAtPath<GameConfig>(AssetPaths.GameConfig);
            BattleSettings settings = config.Battle.Clone();
            var text = new StringBuilder();
            var report = new StringBuilder();
            text.AppendLine("# Pixel Defense - main campaign. Generated by Pixel Defense/Levels/Generate Campaign; edit Plans() and regenerate.");
            text.AppendLine("# body: head-to-tail runs (pattern*slices); col: cannons front-to-back; ? = hidden until at the front.");
            text.AppendLine("version 1");
            text.AppendLine("pack main");
            text.AppendLine();
            text.AppendLine(TutorialLevel);
            report.AppendLine("L01 Hatchling: hand-written tutorial");

            foreach (Plan plan in Plans())
            {
                string level = BuildLevel(plan, settings, out string line);
                text.Append(level);
                text.AppendLine();
                report.AppendLine(line);
            }

            File.WriteAllText(AssetPaths.LevelPack, text.ToString());
            AssetDatabase.ImportAsset(AssetPaths.LevelPack, ImportAssetOptions.ForceUpdate);
            return "Campaign generated:\n" + report;
        }

        // Hand-made first level: two colors in order, two columns, a slow dragon and the tap tutorial.
        private const string TutorialLevel =
            "level L01\nname Hatchling\ntrack spiral\nskin ember\ntutorial tap\nspeed 0.90\nstart 18\nwidth 3\nwindow 3\nslots 5\n" +
            "body O*8 G*6\ncol O12 G9\ncol O12 G9\nend\n";

        private struct Plan
        {
            public string Id;
            public string Name;
            public string Track;
            public string Skin;
            public string Tutorial;
            public int Colors;
            public int Slices;
            public int Window;
            public int Columns;
            public int Slots;
            public float Disorder;
            public float Stripes;
            public float Hidden;
            public float Slack;
            public int MinChunk;
            public int MaxChunk;
            public int MinRun;
            public int MaxRun;
            public float Start;
            public int Seed;
        }

        private static IEnumerable<Plan> Plans()
        {
            string[] tracks = { "spiral", "spiral_cw", "square", "spiral", "square_cw", "spiral_cw" };
            string[] skins = { "ember", "jade", "frost", "venom", "ember", "jade", "frost", "venom" };
            string[] names =
            {
                "Hatchling", "Three Scales", "Coil Crawler", "Slot Squeeze", "Golden Hoard (Boss)", "Striped Menace",
                "Jade Serpent", "Mystery Cannons", "Frost Wyrm", "Shadow Wyrm (Boss)", "Ember Ribbon", "Venom Loop",
                "Rainbow Tail", "Tight Corners", "Molten Monarch (Boss)", "Copper Coil", "Glacier Glide", "Twin Stripes",
                "Hydra Neck", "Obsidian Emperor (Boss)", "Pixel Python", "Lantern Drake", "Crystal Coil", "Thunder Tail",
                "Ancient Horror (Boss)"
            };

            for (int i = 0; i < names.Length; i++)
            {
                int n = i + 1;
                bool boss = n % 5 == 0;
                float t = (float)i / (names.Length - 1);
                var plan = new Plan
                {
                    Id = "L" + n.ToString("D2", CultureInfo.InvariantCulture),
                    Name = names[i],
                    Track = boss ? "spiral_long" : tracks[i % tracks.Length],
                    Skin = boss ? (n % 10 == 0 ? "shadow" : "gold") : skins[i % skins.Length],
                    Tutorial = n == 2 ? "neck" : n == 4 ? "slots" : n == 8 ? "hidden" : n == 7 ? "boosters" : null,
                    Colors = Mathf.Clamp(2 + n / 3, 3, 6),
                    Slices = Mathf.RoundToInt(Mathf.Lerp(36f, 110f, t) * (boss ? 1.25f : 1f)),
                    Window = n < 6 ? 3 : 2,
                    Columns = n < 3 ? 2 : n < 9 ? 3 : n < 18 ? 4 : 5,
                    Slots = 5,
                    Disorder = Mathf.Lerp(0.08f, 0.55f, t) + (boss ? 0.08f : 0f),
                    Stripes = n < 6 ? 0f : Mathf.Lerp(0.2f, 0.4f, t),
                    Hidden = n < 8 ? 0f : Mathf.Lerp(0.12f, 0.3f, t),
                    Slack = boss ? Mathf.Lerp(0.2f, 0.08f, t) : Mathf.Lerp(0.4f, 0.15f, t),
                    MinChunk = 9,
                    MaxChunk = n < 5 ? 24 : n < 12 ? 36 : 45,
                    MinRun = 4,
                    MaxRun = n < 5 ? 10 : 14,
                    Start = 40f,
                    Seed = 1009 * n + 17
                };
                if (n == 1)
                {
                    continue;
                }
                yield return plan;
            }
        }

        private static string BuildLevel(Plan plan, BattleSettings settings, out string reportLine)
        {
            for (int attempt = 0; attempt < Attempts; attempt++)
            {
                var random = new System.Random(plan.Seed + attempt * 7919);
                string body = DesignBody(plan, random, out Dictionary<char, int> counts, out List<char> demand);
                List<string> sequence = DesignSequence(plan, random, counts, demand);
                List<List<string>> columns = Deal(plan, random, sequence);
                string text = Format(plan, body, columns, speed: 1f);
                LevelDefinition level = Parse(text);
                if (level == null)
                {
                    continue;
                }

                int[] moves = ReplayOrder(level, columns, sequence);
                bool solved = moves != null && Replays(level, settings, moves);
                if (!solved)
                {
                    SolveResult result = LevelSolver.Solve(level, settings, SolverBudget);
                    if (!result.Solved)
                    {
                        continue;
                    }
                    moves = result.Moves;
                }

                bool greedy = LevelSolver.Solve(level, settings, 1).GreedyWins;
                float speed = TuneSpeed(text, plan, settings, moves, out BotResult bot, out float startDistance);
                if (speed <= 0f)
                {
                    continue;
                }

                string final = Format(plan, body, columns, speed);
                reportLine = plan.Id + " " + plan.Name + ": slices=" + level.SliceCount + " cannons=" + level.CannonCount +
                             " speed=" + speed.ToString("F2", CultureInfo.InvariantCulture) +
                             " slack=" + (bot.MinDistance / startDistance).ToString("P0", CultureInfo.InvariantCulture) +
                             " botTime=" + bot.Duration.ToString("F0", CultureInfo.InvariantCulture) + "s greedy=" + greedy +
                             " attempt=" + attempt;
                return final;
            }

            reportLine = plan.Id + " FAILED to generate";
            Debug.LogError("Campaign: could not generate " + plan.Id);
            return string.Empty;
        }

        private static string DesignBody(Plan plan, System.Random random, out Dictionary<char, int> counts, out List<char> demand)
        {
            var palette = new List<char>(Vivid);
            Shuffle(palette, random);
            var colors = palette.GetRange(0, plan.Colors);
            counts = new Dictionary<char, int>();
            demand = new List<char>();
            var tokens = new List<string>();
            int remaining = plan.Slices;
            char previous = ' ';
            int colorCursor = 0;
            while (remaining > 0)
            {
                int run = Math.Min(remaining, random.Next(plan.MinRun, plan.MaxRun + 1));
                if (remaining - run > 0 && remaining - run < plan.MinRun)
                {
                    run = remaining;
                }

                char main = colors[colorCursor % colors.Count];
                colorCursor += 1 + (random.NextDouble() < 0.3 ? 1 : 0);
                if (main == previous)
                {
                    main = colors[(colorCursor++) % colors.Count];
                }

                string pattern;
                if (random.NextDouble() < plan.Stripes)
                {
                    char accent = colors[random.Next(colors.Count)];
                    if (accent == main)
                    {
                        accent = colors[(colors.IndexOf(main) + 1) % colors.Count];
                    }
                    pattern = random.NextDouble() < 0.5 ? new string(new[] { main, accent, main }) : new string(new[] { accent, main, accent });
                }
                else
                {
                    pattern = main.ToString();
                }

                tokens.Add(pattern + "*" + run);
                for (int s = 0; s < run; s++)
                {
                    for (int lane = 0; lane < 3; lane++)
                    {
                        char c = pattern.Length == 1 ? pattern[0] : pattern[lane];
                        counts[c] = counts.TryGetValue(c, out int v) ? v + 1 : 1;
                        demand.Add(c);
                    }
                }

                previous = main;
                remaining -= run;
            }

            return string.Join(" ", tokens);
        }

        /// <summary>Just-in-time cannon order: a color's next cannon is queued when its scales are next needed.</summary>
        private static List<string> DesignSequence(Plan plan, System.Random random, Dictionary<char, int> counts, List<char> demand)
        {
            var chunks = new Dictionary<char, Queue<int>>();
            foreach (KeyValuePair<char, int> pair in counts)
            {
                chunks[pair.Key] = new Queue<int>(SplitAmmo(pair.Value, plan, random));
            }

            var supply = new Dictionary<char, int>();
            var sequence = new List<string>();
            foreach (char color in demand)
            {
                supply.TryGetValue(color, out int have);
                if (have > 0)
                {
                    supply[color] = have - 1;
                    continue;
                }

                int ammo = chunks[color].Dequeue();
                sequence.Add(color.ToString() + ammo.ToString(CultureInfo.InvariantCulture));
                supply[color] = ammo - 1;
            }

            // Pull some cannons earlier than needed: they must park in a slot until their color reaches the neck.
            int swaps = Mathf.RoundToInt(sequence.Count * plan.Disorder);
            for (int i = 0; i < swaps; i++)
            {
                int a = random.Next(1, sequence.Count);
                int distance = random.Next(1, 4);
                int b = Math.Max(0, a - distance);
                string moved = sequence[a];
                sequence.RemoveAt(a);
                sequence.Insert(b, moved);
            }
            return sequence;
        }

        private static List<int> SplitAmmo(int total, Plan plan, System.Random random)
        {
            var parts = new List<int>();
            int remaining = total;
            while (remaining > 0)
            {
                if (remaining <= plan.MaxChunk && (remaining < plan.MinChunk * 2 || random.NextDouble() < 0.35))
                {
                    parts.Add(remaining);
                    break;
                }

                int max = Math.Min(plan.MaxChunk, remaining - plan.MinChunk);
                int chunk = random.Next(plan.MinChunk, max + 1);
                chunk = Math.Max(plan.MinChunk, chunk / 3 * 3);
                parts.Add(chunk);
                remaining -= chunk;
            }
            return parts;
        }

        private static List<List<string>> Deal(Plan plan, System.Random random, List<string> sequence)
        {
            var columns = new List<List<string>>();
            for (int c = 0; c < plan.Columns; c++)
            {
                columns.Add(new List<string>());
            }

            for (int i = 0; i < sequence.Count; i++)
            {
                // Prefer shorter columns so stacks stay even, with randomness so the next cannon has to be found.
                int best = random.Next(plan.Columns);
                for (int k = 0; k < 2; k++)
                {
                    int other = random.Next(plan.Columns);
                    if (columns[other].Count < columns[best].Count)
                    {
                        best = other;
                    }
                }

                string token = sequence[i];
                if (columns[best].Count > 0 && random.NextDouble() < plan.Hidden)
                {
                    token = "?" + token;
                }
                columns[best].Add(token);
            }

            columns.RemoveAll(column => column.Count == 0);
            return columns;
        }

        private static string Format(Plan plan, string body, List<List<string>> columns, float speed)
        {
            var text = new StringBuilder();
            text.AppendLine("level " + plan.Id);
            text.AppendLine("name " + plan.Name);
            text.AppendLine("track " + plan.Track);
            text.AppendLine("skin " + plan.Skin);
            if (!string.IsNullOrEmpty(plan.Tutorial))
            {
                text.AppendLine("tutorial " + plan.Tutorial);
            }
            text.AppendLine("speed " + speed.ToString("F2", CultureInfo.InvariantCulture));
            text.AppendLine("start " + plan.Start.ToString("F0", CultureInfo.InvariantCulture));
            text.AppendLine("width 3");
            text.AppendLine("window " + plan.Window);
            text.AppendLine("slots " + plan.Slots);
            text.AppendLine("body " + body);
            foreach (List<string> column in columns)
            {
                text.AppendLine("col " + string.Join(" ", column));
            }
            text.AppendLine("end");
            return text.ToString();
        }

        private static LevelDefinition Parse(string levelText)
        {
            LevelPack pack = LevelParser.Parse("version 1\n" + levelText, "generator");
            if (pack.HasErrors || pack.Levels.Count != 1)
            {
                foreach (LevelIssue issue in pack.Issues)
                {
                    Debug.LogWarning(issue.ToString());
                }
                return null;
            }
            return pack.Levels[0];
        }

        /// <summary>Converts the designed sequence into column taps (each cannon is the front of its column in order).</summary>
        private static int[] ReplayOrder(LevelDefinition level, List<List<string>> columns, List<string> sequence)
        {
            var heads = new int[columns.Count];
            var moves = new List<int>(sequence.Count);
            for (int i = 0; i < sequence.Count; i++)
            {
                int found = -1;
                for (int c = 0; c < columns.Count; c++)
                {
                    if (heads[c] < columns[c].Count && columns[c][heads[c]].TrimStart('?') == sequence[i])
                    {
                        found = c;
                        break;
                    }
                }

                if (found < 0)
                {
                    return null;
                }
                heads[found]++;
                moves.Add(found);
            }
            return moves.ToArray();
        }

        private static bool Replays(LevelDefinition level, BattleSettings settings, int[] moves)
        {
            var battle = new Battle(level, settings, float.MaxValue / 4f) { MovementEnabled = false };
            for (int i = 0; i < moves.Length && battle.Phase == BattlePhase.Playing; i++)
            {
                if (battle.Deploy(moves[i]) != DeployResult.Deployed)
                {
                    return false;
                }
                battle.RunUntilQuiescent(600f);
            }
            return battle.Phase == BattlePhase.Won;
        }

        private static float TuneSpeed(string levelText, Plan plan, BattleSettings settings, int[] moves, out BotResult best, out float startDistance)
        {
            LevelDefinition probe = Parse(levelText);
            TrackShape track = TrackPresets.Create(probe.Track, probe.Width);
            startDistance = track.ContactFront(settings.HeadLength) - probe.Start;
            float low = MinSpeed;
            float high = MaxSpeed;
            best = default;
            float chosen = -1f;
            for (int i = 0; i < 16; i++)
            {
                float speed = (low + high) * 0.5f;
                LevelDefinition level = Parse(levelText.Replace("speed 1.00", "speed " + speed.ToString("F3", CultureInfo.InvariantCulture)));
                BotResult bot = BotPlayer.Play(level, settings, track, moves, BotReaction, waitForSettle: true);
                float slack = bot.Won ? bot.MinDistance / startDistance : -1f;
                if (bot.Won && slack >= plan.Slack)
                {
                    chosen = speed;
                    best = bot;
                    low = speed;
                }
                else
                {
                    high = speed;
                }
            }
            // Hitting the cap means the level is relaxed even at full speed; keep the creep readable instead.
            return chosen > 0f ? Mathf.Floor(chosen * 100f) / 100f : -1f;
        }

        private static void Shuffle<T>(List<T> list, System.Random random)
        {
            for (int i = list.Count - 1; i > 0; i--)
            {
                int j = random.Next(i + 1);
                T tmp = list[i];
                list[i] = list[j];
                list[j] = tmp;
            }
        }
    }
}
