using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using PixelDefense.App;
using PixelDefense.Core;
using UnityEditor;
using UnityEngine;

namespace PixelDefense.EditorTools
{
    /// <summary>
    /// Builds the main campaign deterministically: designs each dragon (color runs, stripes) so every color has a
    /// multiple of 10 scales, splits those into 10/20/40-ammo cannons, derives a just-in-time deploy order, perturbs
    /// it (parking pressure), deals it into columns, proves it solvable, then tunes the crawl speed with a careful
    /// bot to a target safety margin.
    /// </summary>
    public static class CampaignGenerator
    {
        private const int SolverBudget = 150000;
        private const int Attempts = 40;
        private const float MinSpeed = 0.35f;
        private const float MaxSpeed = 6f;

        /// <summary>Tap reaction of the speed-tuning bot; slower than an expert so levels leave room to think.</summary>
        private const float BotReaction = 1.2f;

        /// <summary>Cannon sizes, Pixel Flow style. Every color's scale count is a multiple of the smallest.</summary>
        private static readonly int[] AmmoSizes = { 10, 20, 40 };

        private const int AmmoUnit = 10;
        private const int Lanes = 3;

        /// <summary>Where dragons start (slices past the arena entrance); long bodies trail off-screen behind.</summary>
        private const float DefaultStart = 40f;

        private const int MaxColumns = LevelValidator.MaxColumns;

        private static readonly char[] Vivid = { 'O', 'G', 'B', 'R', 'Y', 'P', 'C', 'K', 'W', 'L' };

        /// <summary>
        /// Boss layouts (L05, L10, ...). Bosses use the same compact tracks as everyone else, so the camera stays as
        /// close as usual; their extra-long bodies simply trail off-screen.
        /// </summary>
        private static readonly string[] BossTracks = { "square", "spiral_cw", "snake", "square_cw", "spiral" };

        /// <summary>Non-boss layouts in campaign order.</summary>
        private static readonly string[] Tracks =
        {
            "spiral_cw", "hairpin", "snake", "zigzag", "square", "hairpin_cw", "snake_cw", "zigzag_cw", "spiral", "snake",
            "square_cw", "spiral_cw", "hairpin", "zigzag", "snake_cw", "snake", "square", "spiral", "zigzag_cw"
        };

        [MenuItem("Pixel Defense/Levels/Generate Campaign", priority = 60)]
        public static void GenerateMenu()
        {
            string report = Generate();
            Debug.Log(report);
        }

        public static string Generate()
        {
            var config = AssetDatabase.LoadAssetAtPath<GameConfig>(AssetPaths.GameConfig);
            BattleSettings settings = config.Battle.Clone();
            var text = new StringBuilder();
            var report = new StringBuilder();
            text.AppendLine("# Pixel Defense - main campaign. Generated by Pixel Defense/Levels/Generate Campaign; edit Plans() and regenerate.");
            text.AppendLine("# body: head-to-tail runs (pattern*slices); col: cannons front-to-back; ? = hidden until at the front.");
            text.AppendLine("version 1");
            text.AppendLine("pack main");
            text.AppendLine();
            text.AppendLine(TutorialLevel);
            report.AppendLine("L01 Hatchling: hand-written tutorial");

            foreach (Plan plan in Plans())
            {
                string level = BuildLevel(plan, settings, out string line);
                text.Append(level);
                text.AppendLine();
                report.AppendLine(line);
            }

            File.WriteAllText(AssetPaths.LevelPack, text.ToString());
            AssetDatabase.ImportAsset(AssetPaths.LevelPack, ImportAssetOptions.ForceUpdate);
            return "Campaign generated:\n" + report;
        }

        // Hand-made first level: two colors in order, two columns, a slow dragon and the tap tutorial.
        private const string TutorialLevel =
            "level L01\nname Hatchling\ntrack spiral\nskin ember\ntutorial tap\nspeed 0.90\nstart 18\nwidth 3\nwindow 3\nslots 5\n" +
            "body O*10 G*10\ncol O20 G10\ncol O10 G20\nend\n";

        private struct Plan
        {
            public string Id;
            public string Name;
            public string Track;
            public string Skin;
            public string Tutorial;
            public int Colors;
            public int Slices;
            public int Window;
            public int Columns;
            public int Slots;
            public float Disorder;
            public float Stripes;
            public float Hidden;
            public float Slack;
            public int MinRun;
            public int MaxRun;
            public float Start;
            public int Seed;

            /// <summary>Relative odds of 10, 20 and 40 ammo cannons.</summary>
            public float[] AmmoWeights;

            /// <summary>Prefer designs a "tap whatever can shoot" player can beat (relaxed after half the attempts).</summary>
            public bool PreferGreedy;
        }

        private static IEnumerable<Plan> Plans()
        {
            string[] skins = { "ember", "jade", "frost", "venom", "ember", "jade", "frost", "venom" };
            int nonBoss = 0;
            string[] names =
            {
                "Hatchling", "Three Scales", "Coil Crawler", "Slot Squeeze", "Golden Hoard (Boss)", "Striped Menace",
                "Jade Serpent", "Mystery Cannons", "Frost Wyrm", "Shadow Wyrm (Boss)", "Ember Ribbon", "Venom Loop",
                "Rainbow Tail", "Tight Corners", "Molten Monarch (Boss)", "Copper Coil", "Glacier Glide", "Twin Stripes",
                "Hydra Neck", "Obsidian Emperor (Boss)", "Pixel Python", "Lantern Drake", "Crystal Coil", "Thunder Tail",
                "Ancient Horror (Boss)"
            };

            for (int i = 0; i < names.Length; i++)
            {
                int n = i + 1;
                bool boss = n % 5 == 0;
                float t = (float)i / (names.Length - 1);
                string track = boss ? BossTracks[(n / 5 - 1) % BossTracks.Length] : n == 1 ? "spiral" : Tracks[nonBoss++ % Tracks.Length];
                var plan = new Plan
                {
                    Id = "L" + n.ToString("D2", CultureInfo.InvariantCulture),
                    Name = names[i],
                    Track = track,
                    Skin = boss ? (n % 10 == 0 ? "shadow" : "gold") : skins[i % skins.Length],
                    Tutorial = n == 2 ? "neck" : n == 4 ? "slots" : n == 8 ? "hidden" : n == 7 ? "boosters" : null,
                    Colors = Mathf.Clamp(2 + n / 3, 3, 6),
                    Slices = Mathf.RoundToInt(Mathf.Lerp(36f, 130f, t) * (boss ? 1.3f : 1f)),
                    Window = n < 6 ? 3 : 2,
                    Columns = n < 3 ? 2 : n < 9 ? 3 : MaxColumns,
                    Slots = 5,
                    Disorder = Mathf.Lerp(0.08f, 0.55f, t) + (boss ? 0.08f : 0f),
                    Stripes = n < 6 ? 0f : Mathf.Lerp(0.2f, 0.4f, t),
                    Hidden = n < 8 ? 0f : Mathf.Lerp(0.12f, 0.3f, t),
                    Slack = boss ? Mathf.Lerp(0.25f, 0.12f, t) : Mathf.Lerp(0.4f, 0.18f, t),
                    MinRun = 4,
                    MaxRun = n < 5 ? 10 : 14,
                    Start = DefaultStart,
                    Seed = 1009 * n + 17,
                    AmmoWeights = n < 5 ? new[] { 0.45f, 0.55f, 0f }
                        : boss ? new[] { 0.2f, 0.4f, 0.4f }
                        : new[] { Mathf.Lerp(0.35f, 0.2f, t), 0.45f, Mathf.Lerp(0.2f, 0.35f, t) },
                    PreferGreedy = !boss && n < 12
                };
                if (n == 1)
                {
                    continue;
                }
                yield return plan;
            }
        }

        private static string BuildLevel(Plan plan, BattleSettings settings, out string reportLine)
        {
            for (int attempt = 0; attempt < Attempts; attempt++)
            {
                var random = new System.Random(plan.Seed + attempt * 7919);
                string body = DesignBody(plan, random, out Dictionary<char, int> counts, out List<char> demand);
                List<string> sequence = DesignSequence(plan, random, counts, demand);
                List<List<string>> columns = Deal(plan, random, sequence);
                string text = Format(plan, body, columns, speed: 1f);
                LevelDefinition level = Parse(text);
                if (level == null)
                {
                    continue;
                }

                int[] moves = ReplayOrder(level, columns, sequence);
                bool solved = moves != null && Replays(level, settings, moves);
                if (!solved)
                {
                    SolveResult result = LevelSolver.Solve(level, settings, SolverBudget);
                    if (!result.Solved)
                    {
                        continue;
                    }
                    moves = result.Moves;
                }

                bool greedy = LevelSolver.Solve(level, settings, 1).GreedyWins;
                if (plan.PreferGreedy && !greedy && attempt < Attempts / 2)
                {
                    continue;
                }

                float speed = TuneSpeed(text, plan, settings, moves, out BotResult bot, out float startDistance);
                if (speed <= 0f)
                {
                    continue;
                }

                string final = Format(plan, body, columns, speed);
                reportLine = plan.Id + " " + plan.Name + " [" + plan.Track + "]: slices=" + level.SliceCount + " cannons=" + level.CannonCount +
                             " speed=" + speed.ToString("F2", CultureInfo.InvariantCulture) +
                             " slack=" + (bot.MinDistance / startDistance).ToString("P0", CultureInfo.InvariantCulture) +
                             " botTime=" + bot.Duration.ToString("F0", CultureInfo.InvariantCulture) + "s greedy=" + greedy +
                             " attempt=" + attempt;
                return final;
            }

            reportLine = plan.Id + " FAILED to generate";
            Debug.LogError("Campaign: could not generate " + plan.Id);
            return string.Empty;
        }

        private sealed class Run
        {
            public string Pattern;
            public char Main;
            public int Slices;

            public bool Solid => Pattern.Length == 1;
        }

        private static string DesignBody(Plan plan, System.Random random, out Dictionary<char, int> counts, out List<char> demand)
        {
            var palette = new List<char>(Vivid);
            Shuffle(palette, random);
            var colors = palette.GetRange(0, plan.Colors);
            var runs = new List<Run>();
            int remaining = plan.Slices;
            char previous = ' ';
            int colorCursor = 0;
            while (remaining > 0)
            {
                int length = Math.Min(remaining, random.Next(plan.MinRun, plan.MaxRun + 1));
                if (remaining - length > 0 && remaining - length < plan.MinRun)
                {
                    length = remaining;
                }

                char main = colors[colorCursor % colors.Count];
                colorCursor += 1 + (random.NextDouble() < 0.3 ? 1 : 0);
                if (main == previous)
                {
                    main = colors[(colorCursor++) % colors.Count];
                }

                string pattern;
                if (random.NextDouble() < plan.Stripes)
                {
                    char accent = colors[random.Next(colors.Count)];
                    if (accent == main)
                    {
                        accent = colors[(colors.IndexOf(main) + 1) % colors.Count];
                    }
                    pattern = random.NextDouble() < 0.5 ? new string(new[] { main, accent, main }) : new string(new[] { accent, main, accent });
                }
                else
                {
                    pattern = main.ToString();
                }

                runs.Add(new Run { Pattern = pattern, Main = main, Slices = length });
                previous = main;
                remaining -= length;
            }

            RoundColorTotals(runs, plan, random);

            counts = new Dictionary<char, int>();
            demand = new List<char>();
            var tokens = new List<string>(runs.Count);
            foreach (Run run in runs)
            {
                tokens.Add(run.Pattern + "*" + run.Slices.ToString(CultureInfo.InvariantCulture));
                for (int s = 0; s < run.Slices; s++)
                {
                    for (int lane = 0; lane < Lanes; lane++)
                    {
                        char c = run.Solid ? run.Pattern[0] : run.Pattern[lane];
                        counts[c] = counts.TryGetValue(c, out int v) ? v + 1 : 1;
                        demand.Add(c);
                    }
                }
            }

            return string.Join(" ", tokens);
        }

        /// <summary>
        /// Makes every color's scale count a multiple of <see cref="AmmoUnit"/> by stretching or trimming one solid
        /// run of that color: a solid slice holds 3 scales and 3 is invertible mod 10, so one run always fixes it.
        /// Colors that only appear in stripes first get a short solid run of their own.
        /// </summary>
        private static void RoundColorTotals(List<Run> runs, Plan plan, System.Random random)
        {
            var colors = new List<char>();
            foreach (Run run in runs)
            {
                foreach (char c in run.Pattern)
                {
                    if (!colors.Contains(c))
                    {
                        colors.Add(c);
                    }
                }
            }

            foreach (char color in colors)
            {
                if (runs.Exists(r => r.Solid && r.Main == color))
                {
                    continue;
                }

                int at = random.Next(1, runs.Count + 1);
                while (at < runs.Count && (runs[at - 1].Main == color || runs[at].Main == color))
                {
                    at++;
                }
                runs.Insert(at, new Run { Pattern = color.ToString(), Main = color, Slices = plan.MinRun });
            }

            foreach (char color in colors)
            {
                int total = 0;
                foreach (Run run in runs)
                {
                    foreach (char c in run.Pattern)
                    {
                        if (c == color)
                        {
                            total += run.Solid ? run.Slices * Lanes : run.Slices;
                        }
                    }
                }

                int remainder = total % AmmoUnit;
                if (remainder == 0)
                {
                    continue;
                }

                // 3 * 7 = 21 = 1 (mod 10): adding d slices adds 3d scales, so d = -7 * remainder (mod 10).
                int grow = ((-7 * remainder) % AmmoUnit + AmmoUnit) % AmmoUnit;
                Run target = null;
                foreach (Run run in runs)
                {
                    if (run.Solid && run.Main == color && (target == null || run.Slices > target.Slices))
                    {
                        target = run;
                    }
                }

                int delta = grow > AmmoUnit / 2 && target.Slices + grow - AmmoUnit >= plan.MinRun ? grow - AmmoUnit : grow;
                target.Slices += delta;
            }
        }

        /// <summary>Just-in-time cannon order: a color's next cannon is queued when its scales are next needed.</summary>
        private static List<string> DesignSequence(Plan plan, System.Random random, Dictionary<char, int> counts, List<char> demand)
        {
            var chunks = new Dictionary<char, Queue<int>>();
            foreach (KeyValuePair<char, int> pair in counts)
            {
                chunks[pair.Key] = new Queue<int>(SplitAmmo(pair.Value, plan, random));
            }

            var supply = new Dictionary<char, int>();
            var sequence = new List<string>();
            foreach (char color in demand)
            {
                supply.TryGetValue(color, out int have);
                if (have > 0)
                {
                    supply[color] = have - 1;
                    continue;
                }

                int ammo = chunks[color].Dequeue();
                sequence.Add(color.ToString() + ammo.ToString(CultureInfo.InvariantCulture));
                supply[color] = ammo - 1;
            }

            // Pull some cannons earlier than needed: they must park in a slot until their color reaches the neck.
            int swaps = Mathf.RoundToInt(sequence.Count * plan.Disorder);
            for (int i = 0; i < swaps; i++)
            {
                int a = random.Next(1, sequence.Count);
                int distance = random.Next(1, 4);
                int b = Math.Max(0, a - distance);
                string moved = sequence[a];
                sequence.RemoveAt(a);
                sequence.Insert(b, moved);
            }
            return sequence;
        }

        /// <summary>Splits a color's scales (a multiple of 10) into 10, 20 and 40 ammo cannons by the plan's odds.</summary>
        private static List<int> SplitAmmo(int total, Plan plan, System.Random random)
        {
            var parts = new List<int>();
            int remaining = total;
            while (remaining > 0)
            {
                float sum = 0f;
                for (int k = 0; k < AmmoSizes.Length; k++)
                {
                    if (AmmoSizes[k] <= remaining)
                    {
                        sum += plan.AmmoWeights[k];
                    }
                }

                int chunk = AmmoSizes[0];
                float roll = (float)random.NextDouble() * sum;
                for (int k = 0; k < AmmoSizes.Length; k++)
                {
                    if (AmmoSizes[k] > remaining || plan.AmmoWeights[k] <= 0f)
                    {
                        continue;
                    }

                    chunk = AmmoSizes[k];
                    roll -= plan.AmmoWeights[k];
                    if (roll <= 0f)
                    {
                        break;
                    }
                }

                parts.Add(chunk);
                remaining -= chunk;
            }
            return parts;
        }

        private static List<List<string>> Deal(Plan plan, System.Random random, List<string> sequence)
        {
            var columns = new List<List<string>>();
            for (int c = 0; c < plan.Columns; c++)
            {
                columns.Add(new List<string>());
            }

            for (int i = 0; i < sequence.Count; i++)
            {
                // Prefer shorter columns so stacks stay even, with randomness so the next cannon has to be found.
                int best = random.Next(plan.Columns);
                for (int k = 0; k < 2; k++)
                {
                    int other = random.Next(plan.Columns);
                    if (columns[other].Count < columns[best].Count)
                    {
                        best = other;
                    }
                }

                string token = sequence[i];
                if (columns[best].Count > 0 && random.NextDouble() < plan.Hidden)
                {
                    token = "?" + token;
                }
                columns[best].Add(token);
            }

            columns.RemoveAll(column => column.Count == 0);
            return columns;
        }

        private static string Format(Plan plan, string body, List<List<string>> columns, float speed)
        {
            var text = new StringBuilder();
            text.AppendLine("level " + plan.Id);
            text.AppendLine("name " + plan.Name);
            text.AppendLine("track " + plan.Track);
            text.AppendLine("skin " + plan.Skin);
            if (!string.IsNullOrEmpty(plan.Tutorial))
            {
                text.AppendLine("tutorial " + plan.Tutorial);
            }
            text.AppendLine("speed " + speed.ToString("F2", CultureInfo.InvariantCulture));
            text.AppendLine("start " + plan.Start.ToString("F0", CultureInfo.InvariantCulture));
            text.AppendLine("width 3");
            text.AppendLine("window " + plan.Window);
            text.AppendLine("slots " + plan.Slots);
            text.AppendLine("body " + body);
            foreach (List<string> column in columns)
            {
                text.AppendLine("col " + string.Join(" ", column));
            }
            text.AppendLine("end");
            return text.ToString();
        }

        private static LevelDefinition Parse(string levelText)
        {
            LevelPack pack = LevelParser.Parse("version 1\n" + levelText, "generator");
            if (pack.HasErrors || pack.Levels.Count != 1)
            {
                foreach (LevelIssue issue in pack.Issues)
                {
                    Debug.LogWarning(issue.ToString());
                }
                return null;
            }
            return pack.Levels[0];
        }

        /// <summary>Converts the designed sequence into column taps (each cannon is the front of its column in order).</summary>
        private static int[] ReplayOrder(LevelDefinition level, List<List<string>> columns, List<string> sequence)
        {
            var heads = new int[columns.Count];
            var moves = new List<int>(sequence.Count);
            for (int i = 0; i < sequence.Count; i++)
            {
                int found = -1;
                for (int c = 0; c < columns.Count; c++)
                {
                    if (heads[c] < columns[c].Count && columns[c][heads[c]].TrimStart('?') == sequence[i])
                    {
                        found = c;
                        break;
                    }
                }

                if (found < 0)
                {
                    return null;
                }
                heads[found]++;
                moves.Add(found);
            }
            return moves.ToArray();
        }

        private static bool Replays(LevelDefinition level, BattleSettings settings, int[] moves)
        {
            var battle = new Battle(level, settings, float.MaxValue / 4f) { MovementEnabled = false };
            for (int i = 0; i < moves.Length && battle.Phase == BattlePhase.Playing; i++)
            {
                if (battle.Deploy(moves[i]) != DeployResult.Deployed)
                {
                    return false;
                }
                battle.RunUntilQuiescent(600f);
            }
            return battle.Phase == BattlePhase.Won;
        }

        private static float TuneSpeed(string levelText, Plan plan, BattleSettings settings, int[] moves, out BotResult best, out float startDistance)
        {
            LevelDefinition probe = Parse(levelText);
            TrackShape track = TrackPresets.Create(probe.Track, probe.Width);
            startDistance = track.ContactFront(settings.HeadLength) - probe.Start;
            float low = MinSpeed;
            float high = MaxSpeed;
            best = default;
            float chosen = -1f;
            for (int i = 0; i < 16; i++)
            {
                float speed = (low + high) * 0.5f;
                LevelDefinition level = Parse(levelText.Replace("speed 1.00", "speed " + speed.ToString("F3", CultureInfo.InvariantCulture)));
                BotResult bot = BotPlayer.Play(level, settings, track, moves, BotReaction, waitForSettle: true);
                float slack = bot.Won ? bot.MinDistance / startDistance : -1f;
                if (bot.Won && slack >= plan.Slack)
                {
                    chosen = speed;
                    best = bot;
                    low = speed;
                }
                else
                {
                    high = speed;
                }
            }
            // Hitting the cap means the level is relaxed even at full speed; keep the creep readable instead.
            return chosen > 0f ? Mathf.Floor(chosen * 100f) / 100f : -1f;
        }

        private static void Shuffle<T>(List<T> list, System.Random random)
        {
            for (int i = list.Count - 1; i > 0; i--)
            {
                int j = random.Next(i + 1);
                T tmp = list[i];
                list[i] = list[j];
                list[j] = tmp;
            }
        }
    }
}
